### ISSUE TITLE
As a Developer, I want to validate the username and password for logging into the application

### ISSUE THREAD

**Issue by Maruthi158** [Maruthi158/BuddyBearcat#8]
**Acceptance criteria**

1.Entering invalid email id or password should display some error message

2.Entering valid details should successfully logging into the application

**Comment by GUNDAANUTEJ** [comment]
I have validated with username, password for loggin into the application.

**Comment by RoopinVipparthi** [comment]
I have validated user name and password for the login page and hence i am closing the story
