### ISSUE TITLE
As a Developer,I want to validate the sign up for the application form

### ISSUE THREAD

**Issue by Maruthi158** [Maruthi158/BuddyBearcat#9]
**Acceptance Criteria**

1.As a Developer I want to check if all the required fields are filled or not while submitting the application.

**Comment by balumalladi** [comment]
I have validated all the sign-up fields required for the validation of new users.

**Comment by RoopinVipparthi** [comment]
I have worked with team to validate all the fields in the sign up form hence I am closing the story.

**Comment by RonaldoS542274** [comment]
I have validated user name and password for the login page.
